version: '2'
services:  
  unit-test:
    image: node:12
    command: npm run test
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: ".env"
    volumes:
      - ".:/usr/src/app/"
      - "./node_modules/:/usr/src/app/node_modules/"
    restart: always
    ports:
      - '3000:3000'
      - '9229:9229'
    expose:
      - '80'